import pandas as pd
import streamlit as st

from src.live_operations import fetch_operations_snapshot
from src.operational_file_ingest import read_operational_upload
from src.operational_hazards import configured_hazard_source, geojson_to_gdf, validate_geojson_hazard
from src.operational_sources import configured_operational_urls, fetch_operational_habitations, fetch_operational_shelters
from src.operational_workspace import normalize_operational_habitations, normalize_operational_shelters, serialize_workspace
from src.pipeline import calculate_summary, enrich_habitations, enrich_shelters
from src.streamlit_workspace import resolve_operational_hazard, resolve_operational_workspace
from src.ui_theme import inject_global_css, render_data_mode_indicator, render_disclaimer, render_kpi_strip, render_page_header

st.set_page_config(page_title="Operational Data", page_icon="DATA", layout="wide")
inject_global_css()
render_page_header(
    "Operational Data Workspace",
    "Activate validated habitation, relocation-site and calibrated hazard sources for every operational module.",
)

st.info(
    "This workspace is the production-data gateway. Reachability does not prove authority: source ownership, timestamps, field definitions and hazard calibration must be verified."
)

# This management page deliberately bypasses the strict-mode stop so operators
# can recover from a broken/missing configured feed by activating validated uploads.
resolved = None
try:
    resolved = resolve_operational_workspace(auto_configured=True, enforce_required=False)
except Exception as exc:
    st.warning(f"Configured operational feeds could not be auto-loaded: {exc}")

configured = configured_operational_urls()
configured_hazard = configured_hazard_source()

st.markdown("### Source configuration")
config_cols = st.columns(3)
config_cols[0].metric("Habitation feed", "Configured" if configured.get("habitations") else "Not configured")
config_cols[1].metric("Relocation-site feed", "Configured" if configured.get("shelters") else "Not configured")
config_cols[2].metric(
    "Calibrated hazard feed",
    "Ready" if configured_hazard.get("url") and configured_hazard.get("calibration_confirmed") else "Not ready",
)
st.caption(
    "Deployment variables: `SIH_HABITATION_CSV_URL`, `SIH_SHELTER_CSV_URL`, `SIH_HAZARD_GEOJSON_URL`, "
    "`SIH_HAZARD_CALIBRATION_CONFIRMED`, optional `SIH_HAZARD_SOURCE_LABEL`."
)

source_mode = st.segmented_control(
    "Settlement/site source",
    ["Current / configured", "Upload files", "Use HTTPS URLs", "Refresh configured feeds"],
    default="Current / configured",
)
label = st.text_input("Operational area label", placeholder="e.g. Wayanad District, Kerala")

if source_mode == "Upload files":
    st.caption("Accepted settlement/site uploads: CSV or Point GeoJSON/JSON. GeoJSON Point geometry supplies latitude/longitude automatically.")
    left, right = st.columns(2, gap="large")
    with left:
        habitation_upload = st.file_uploader("Habitation / settlement dataset", type=["csv", "geojson", "json"], key="ops_hab")
    with right:
        shelter_upload = st.file_uploader("Shelter / relocation-site dataset", type=["csv", "geojson", "json"], key="ops_shelter")
    if st.button("Validate and activate uploaded workspace", type="primary", width="stretch", disabled=not (habitation_upload and shelter_upload)):
        try:
            habitations_raw, h_assessment = normalize_operational_habitations(read_operational_upload(habitation_upload))
            shelters_raw, s_assessment = normalize_operational_shelters(read_operational_upload(shelter_upload))
            st.session_state["operational_workspace"] = serialize_workspace(habitations_raw, shelters_raw, label=label or "Operational upload")
            st.session_state["operational_habitation_assessment"] = h_assessment
            st.session_state["operational_shelter_assessment"] = s_assessment
            st.success("Uploaded operational workspace activated for this browser session.")
            st.rerun()
        except Exception as exc:
            st.error(f"Could not activate uploaded data: {exc}")

elif source_mode == "Use HTTPS URLs":
    st.caption(
        "Paste public HTTPS CSV or Point GeoJSON/JSON endpoints, including bounded WFS or ArcGIS GeoJSON query URLs generated by the GIS Source Inspector. "
        "Local/private-network targets and URLs containing embedded credentials are rejected."
    )
    left, right = st.columns(2, gap="large")
    with left:
        habitation_url = st.text_input("Habitation / settlement HTTPS URL", key="ops_session_habitation_url")
    with right:
        shelter_url = st.text_input("Shelter / relocation-site HTTPS URL", key="ops_session_shelter_url")
    ready = bool(habitation_url.strip() and shelter_url.strip())
    if st.button("Fetch, validate and activate HTTPS workspace", type="primary", width="stretch", disabled=not ready):
        try:
            with st.spinner("Fetching and validating public operational sources..."):
                h_result = fetch_operational_habitations(habitation_url.strip())
                s_result = fetch_operational_shelters(shelter_url.strip())
            st.session_state["operational_workspace"] = serialize_workspace(
                h_result["data"], s_result["data"], label=label or "Session HTTPS operational feeds"
            )
            st.session_state["operational_habitation_assessment"] = h_result["assessment"]
            st.session_state["operational_shelter_assessment"] = s_result["assessment"]
            st.session_state["operational_feed_status"] = {
                "habitations": {k: h_result.get(k) for k in ["mode", "stale", "fetched_at", "source_url", "format"]},
                "shelters": {k: s_result.get(k) for k in ["mode", "stale", "fetched_at", "source_url", "format"]},
            }
            st.success("HTTPS operational workspace activated for this browser session.")
            st.rerun()
        except Exception as exc:
            st.error(f"HTTPS operational source activation failed: {exc}")

elif source_mode == "Refresh configured feeds":
    if not (configured.get("habitations") and configured.get("shelters")):
        st.warning("Both operational HTTPS feed URLs must be configured before refresh.")
    if st.button("Fetch, validate and activate configured feeds", type="primary", width="stretch", disabled=not (configured.get("habitations") and configured.get("shelters"))):
        try:
            with st.spinner("Fetching configured operational datasets..."):
                h_result = fetch_operational_habitations()
                s_result = fetch_operational_shelters()
            st.session_state["operational_workspace"] = serialize_workspace(h_result["data"], s_result["data"], label=label or "Configured operational feeds")
            st.session_state["operational_habitation_assessment"] = h_result["assessment"]
            st.session_state["operational_shelter_assessment"] = s_result["assessment"]
            st.session_state["operational_feed_status"] = {
                "habitations": {k: h_result.get(k) for k in ["mode", "stale", "fetched_at", "source_url", "format"]},
                "shelters": {k: s_result.get(k) for k in ["mode", "stale", "fetched_at", "source_url", "format"]},
            }
            st.success("Configured operational feeds activated.")
            st.rerun()
        except Exception as exc:
            st.error(f"Configured feed refresh failed: {exc}")

# Resolve again after any activation action; strict production mode remains
# bypassed only on this management page so the upload/recovery workflow is usable.
try:
    resolved = resolve_operational_workspace(auto_configured=True, enforce_required=False)
except Exception as exc:
    resolved = None
    st.error(f"Operational workspace validation failed: {exc}")

if not resolved:
    st.warning("No operational workspace is active. Upload both datasets, paste both public HTTPS sources, or configure both deployment feeds.")
    render_disclaimer()
    st.stop()

payload = resolved["payload"]
habitations_raw = resolved["habitations"]
shelters_raw = resolved["shelters"]

meta = st.columns(5)
meta[0].metric("Operational area", payload.get("label", "Operational dataset"))
meta[1].metric("Origin", str(resolved.get("origin", "session")).replace("_", " ").title())
meta[2].metric("Habitation mode", payload.get("habitation_mode", "UNVERIFIED"))
meta[3].metric("Shelter mode", payload.get("shelter_mode", "UNVERIFIED"))
meta[4].metric("Records", f"{len(habitations_raw)} + {len(shelters_raw)}")

mode = payload.get("habitation_mode", "UNVERIFIED")
if mode in {"LIVE", "CACHED", "DEMO"}:
    render_data_mode_indicator(mode)
else:
    st.warning("Habitation provenance is not fully verified. Do not present it as authoritative until source evidence is confirmed.")

feed_status = st.session_state.get("operational_feed_status")
if feed_status:
    with st.expander("Settlement/site feed provenance", expanded=False):
        st.json(feed_status)

st.markdown("### Calibrated hazard layer")
hazard_upload = st.file_uploader(
    "Upload calibrated hazard polygons GeoJSON",
    type=["geojson", "json"],
    key="ops_hazard_geojson",
    help="Every feature must contain numeric hazard_score from 0–100. Activate only when the source-specific mapping is documented.",
)
if hazard_upload is not None:
    try:
        hazard_text = hazard_upload.getvalue().decode("utf-8")
        checked = validate_geojson_hazard(hazard_text)
        st.success(f"GeoJSON valid: {checked['feature_count']} feature(s).")
        confirmed = st.checkbox("I confirm this source's hazard_score mapping is documented and approved for analytical use", value=False)
        if st.button("Activate uploaded calibrated hazard", disabled=not confirmed, width="stretch"):
            st.session_state["operational_hazard_geojson"] = hazard_text
            st.session_state["operational_hazard_name"] = hazard_upload.name
            st.success("Uploaded calibrated hazard layer activated.")
            st.rerun()
    except Exception as exc:
        st.error(f"Hazard layer rejected: {exc}")

hazard_resolved = None
try:
    hazard_resolved = resolve_operational_hazard(auto_configured=True)
except Exception as exc:
    st.warning(f"Configured hazard source is unavailable: {exc}")

if hazard_resolved:
    hcols = st.columns(4)
    hcols[0].metric("Hazard source", str(hazard_resolved.get("label", "Calibrated GeoJSON")))
    hcols[1].metric("Origin", str(hazard_resolved.get("origin", "session")).replace("_", " ").title())
    hcols[2].metric("Mode", hazard_resolved.get("mode", "SESSION"))
    hcols[3].metric("Features", hazard_resolved.get("feature_count", "—"))
    if hazard_resolved.get("stale"):
        st.warning("The calibrated hazard source is being served from cache because the latest refresh was unavailable.")
else:
    st.info("No calibrated hazard layer is active. Stored habitation hazard_score values can still be used, but their provenance must be verified separately.")

hazard_profile = st.selectbox(
    "Analytical hazard profile",
    ["stored", "combined", "flood", "cyclone", "landslide", "earthquake", "drought"],
    index=0,
    format_func=lambda value: "Stored / calibrated GIS" if value == "stored" else value.title(),
)

try:
    hazard_data = None
    if hazard_profile == "stored" and hazard_resolved:
        hazard_data = geojson_to_gdf(hazard_resolved["geojson"])
    habitations = enrich_habitations(habitations_raw, hazard_data=hazard_data, hazard_type=hazard_profile, add_coordination_zones=False)
    shelters = enrich_shelters(shelters_raw)
    summary = calculate_summary(habitations, shelters)
except Exception as exc:
    st.error(f"Operational analysis could not run: {exc}")
    st.caption("Stored/GIS mode requires a verified stored hazard_score or a calibrated GeoJSON hazard layer.")
    render_disclaimer()
    st.stop()

render_kpi_strip([
    ("Habitations", f"{summary['habitations_monitored']:,}", "Operational records"),
    ("Critical", f"{summary['critical_red_zones']:,}", "Deterministic classification"),
    ("Population at Risk", f"{summary['population_at_risk']:,}", "HIGH + CRITICAL"),
    ("Immediate Relocation", f"{summary['immediate_relocation_population']:,}", "Decision-support priority"),
    ("Available Capacity", f"{int(summary['available_shelter_capacity']):,}", "After limiting-resource constraints"),
])

st.markdown("### Priority register")
cols = [c for c in ["name", "population", "hazard_score", "risk_score", "risk_level", "relocation_priority", "risk_drivers"] if c in habitations.columns]
st.dataframe(habitations[cols].sort_values("risk_score", ascending=False), width="stretch", hide_index=True)

st.markdown("### Live context at operational geography")
center = payload["center"]
if st.button("Refresh live context", width="stretch"):
    with st.spinner("Refreshing weather, air quality and nearby event sources concurrently..."):
        st.session_state["ops_workspace_live_snapshot"] = fetch_operations_snapshot(
            payload.get("label", "Operational area"),
            latitude=float(center["latitude"]),
            longitude=float(center["longitude"]),
            days=7,
            radius_km=300,
            min_magnitude=2.5,
        )

snapshot = st.session_state.get("ops_workspace_live_snapshot")
if snapshot:
    health = pd.DataFrame(snapshot.get("source_health", []))
    if not health.empty:
        st.dataframe(health.astype(str), width="stretch", hide_index=True)
    st.caption("Live observations remain corroborating evidence only; they do not silently mutate H/E/V/A.")

with st.expander("If an official source cannot be fetched", expanded=False):
    st.markdown(
        "Send the public source URL plus one sample/download: CSV/XLSX, GeoJSON/Shapefile/GeoTIFF, WMS/WFS/ArcGIS REST layer details, or API docs with a redacted JSON/XML sample. "
        "For login/token/IP-whitelisted services, do not paste secrets in chat; provide the public schema and configure credentials in deployment secrets."
    )

if st.button("Clear browser-session workspace", type="secondary"):
    for key in [
        "operational_workspace", "operational_habitation_assessment", "operational_shelter_assessment",
        "operational_feed_status", "ops_workspace_live_snapshot", "operational_hazard_geojson", "operational_hazard_name",
    ]:
        st.session_state.pop(key, None)
    st.rerun()

render_disclaimer()
