from __future__ import annotations

import os
from functools import lru_cache
from pathlib import Path

from src.spatial_analysis import haversine_km


def _fallback_route(origin: tuple[float, float], destination: tuple[float, float]) -> dict:
    distance = haversine_km(origin[0], origin[1], destination[0], destination[1])
    return {
        "distance_km": round(distance, 2),
        "travel_time_min": None,
        "routing_mode": "haversine_fallback",
        "route_geometry": [
            [float(origin[0]), float(origin[1])],
            [float(destination[0]), float(destination[1])],
        ],
        "route_status": "STRAIGHT_LINE_FALLBACK",
    }


@lru_cache(maxsize=8)
def _load_graph(path_str: str):
    import osmnx as ox

    return ox.load_graphml(path_str)


def _edge_geometry(graph, u, v, data) -> list[list[float]]:
    """Return ordered [[lat, lon], ...] geometry for one OSM edge."""
    geometry = data.get("geometry")
    coords: list[list[float]] = []

    if geometry is not None and hasattr(geometry, "coords"):
        coords = [[float(lat), float(lon)] for lon, lat in geometry.coords]
    elif isinstance(geometry, str) and "LINESTRING" in geometry.upper():
        try:
            from shapely import wkt

            geom = wkt.loads(geometry)
            coords = [[float(lat), float(lon)] for lon, lat in geom.coords]
        except Exception:
            coords = []

    if not coords:
        coords = [
            [float(graph.nodes[u]["y"]), float(graph.nodes[u]["x"])],
            [float(graph.nodes[v]["y"]), float(graph.nodes[v]["x"])],
        ]

    if len(coords) >= 2:
        u_lat = float(graph.nodes[u]["y"])
        u_lon = float(graph.nodes[u]["x"])
        start_d = (coords[0][0] - u_lat) ** 2 + (coords[0][1] - u_lon) ** 2
        end_d = (coords[-1][0] - u_lat) ** 2 + (coords[-1][1] - u_lon) ** 2
        if end_d < start_d:
            coords.reverse()
    return coords


def estimate_route(
    origin: tuple[float, float],
    destination: tuple[float, float],
    graphml_path: str | Path | None = None,
    average_speed_kmph: float = 30.0,
) -> dict:
    """Estimate a route using a cached OSM GraphML file when available.

    The optional `SIH_ROAD_GRAPHML` environment variable can point to a cached
    graph generated by `scripts/cache_road_network.py`. Cached mode follows the
    shortest available OSM road path by edge length and returns display geometry.
    If no usable cache exists, the function returns a clearly-labelled straight-
    line haversine fallback. It does not claim live traffic or congestion data.
    """
    configured_path = graphml_path or os.getenv("SIH_ROAD_GRAPHML")
    if not configured_path:
        return _fallback_route(origin, destination)

    path = Path(configured_path)
    if not path.exists():
        return _fallback_route(origin, destination)

    try:
        import networkx as nx
        import osmnx as ox

        graph = _load_graph(str(path))
        origin_node = ox.distance.nearest_nodes(graph, X=float(origin[1]), Y=float(origin[0]))
        destination_node = ox.distance.nearest_nodes(
            graph, X=float(destination[1]), Y=float(destination[0])
        )
        node_path = nx.shortest_path(graph, origin_node, destination_node, weight="length")

        length_m = 0.0
        road_coords: list[list[float]] = []
        for u, v in zip(node_path[:-1], node_path[1:]):
            options = graph.get_edge_data(u, v) or {}
            if not options:
                continue
            best_key = min(options, key=lambda key: float(options[key].get("length", float("inf"))))
            data = options[best_key]
            length_m += float(data.get("length", 0.0) or 0.0)
            segment = _edge_geometry(graph, u, v, data)
            if road_coords and segment and road_coords[-1] == segment[0]:
                road_coords.extend(segment[1:])
            else:
                road_coords.extend(segment)

        distance_km = length_m / 1000.0
        travel_time_min = None
        if average_speed_kmph > 0:
            travel_time_min = distance_km / average_speed_kmph * 60.0

        geometry = [[float(origin[0]), float(origin[1])]]
        for point in road_coords:
            if geometry[-1] != point:
                geometry.append(point)
        destination_point = [float(destination[0]), float(destination[1])]
        if geometry[-1] != destination_point:
            geometry.append(destination_point)

        return {
            "distance_km": round(distance_km, 2),
            "travel_time_min": round(travel_time_min, 1) if travel_time_min is not None else None,
            "routing_mode": "cached_osm_graph",
            "graphml_path": str(path),
            "route_geometry": geometry,
            "route_status": "ROAD_NETWORK_ROUTE",
        }
    except Exception:
        # Routing must never break the Tier-1 emergency-operations workflow.
        return _fallback_route(origin, destination)
