from __future__ import annotations

import os
from pathlib import Path

from src.spatial_analysis import haversine_km


def _fallback_route(origin: tuple[float, float], destination: tuple[float, float]) -> dict:
    distance = haversine_km(origin[0], origin[1], destination[0], destination[1])
    return {
        "distance_km": round(distance, 2),
        "travel_time_min": None,
        "routing_mode": "haversine_fallback",
    }


def estimate_route(
    origin: tuple[float, float],
    destination: tuple[float, float],
    graphml_path: str | Path | None = None,
    average_speed_kmph: float = 30.0,
) -> dict:
    """Estimate a route using a cached OSM GraphML file when available.

    The optional `SIH_ROAD_GRAPHML` environment variable can point to a cached
    graph generated by `scripts/cache_road_network.py`. If no usable cache is
    available, the function returns a clearly-labelled haversine fallback.
    """
    configured_path = graphml_path or os.getenv("SIH_ROAD_GRAPHML")
    if not configured_path:
        return _fallback_route(origin, destination)

    path = Path(configured_path)
    if not path.exists():
        return _fallback_route(origin, destination)

    try:
        import networkx as nx
        import osmnx as ox

        graph = ox.load_graphml(path)
        origin_node = ox.distance.nearest_nodes(graph, X=origin[1], Y=origin[0])
        destination_node = ox.distance.nearest_nodes(
            graph, X=destination[1], Y=destination[0]
        )
        length_m = nx.shortest_path_length(
            graph, origin_node, destination_node, weight="length"
        )
        distance_km = float(length_m) / 1000.0
        travel_time_min = None
        if average_speed_kmph > 0:
            travel_time_min = distance_km / average_speed_kmph * 60.0

        return {
            "distance_km": round(distance_km, 2),
            "travel_time_min": round(travel_time_min, 1) if travel_time_min is not None else None,
            "routing_mode": "cached_osm_graph",
            "graphml_path": str(path),
        }
    except Exception:
        # Routing failure must not break the emergency-operations demo. The
        # caller sees an explicit fallback mode instead of a silent failure.
        return _fallback_route(origin, destination)
