[theme]
base = "dark"
primaryColor = "#68AEFC"
backgroundColor = "#08111C"
secondaryBackgroundColor = "#101B29"
textColor = "#EEF5FB"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 50

[runner]
fastReruns = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = "stacktrace"
toolbarMode = "minimal"
